// Generated by CoffeeScript 1.12.5
var argreader;

argreader = module.exports = function(arg) {
  var allowEmpty, description, example, multiple, name, optional, ref, ref1, ref2, ref3, shortcut, type;
  if (arg == null) {
    throw new TypeError("Must provide arg.");
  }
  if (typeof arg !== "object") {
    throw new TypeError("Arg must be an object.");
  }
  name = arg.name, description = arg.description, type = (ref = arg.type) != null ? ref : "string", optional = (ref1 = arg.optional) != null ? ref1 : true, shortcut = arg.shortcut, example = arg.example, multiple = (ref2 = arg.multiple) != null ? ref2 : false, allowEmpty = (ref3 = arg.allowEmpty) != null ? ref3 : false;
  if (name == null) {
    throw new TypeError("Arg must have a name.");
  }
  switch (type) {
    case "string":
    case "number":
    case "boolean":
    case "path":
    case "array":
      null;
      break;
    default:
      throw new TypeError("Invalid type!");
  }
  name = name.toString();
  multiple = !!multiple;
  optional = !!optional;
  example = example != null ? example.toString() : example;
  shortcut = shortcut ? shortcut.toString() : shortcut;
  description = description ? description.toString() : description;
  allowEmpty = !!allowEmpty;
  return {
    name: name,
    description: description,
    type: type,
    optional: optional,
    shortcut: shortcut,
    example: example,
    multiple: multiple,
    allowEmpty: allowEmpty
  };
};
