// Generated by CoffeeScript 1.12.5
module.exports = {
  strict: false,
  caseSensitive: false,
  notFoundStr: "Invalid argument {arg}!",
  invalidType: "The argument {arg} requires the type {type}!",
  repeatedArg: "The argument {arg} was already used!",
  emptyArgErr: "The argument {arg} must not be empty!",
  pathSymbol: "/",
  arraySymbol: ",",
  parseCache: 1
};
